In [26]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

from sklearn.impute import SimpleImputer, MissingIndicator

In [6]:
df = pd.read_csv('train.csv',usecols=['Age','Fare','Survived'])

In [8]:
df.head()

Survived   Age     Fare
0         0  22.0   7.2500
1         1  38.0  71.2833
2         1  26.0   7.9250
3         1  35.0  53.1000
4         0  35.0   8.0500

In [10]:
x = df.drop(columns='Survived')
y = df['Survived']

In [14]:
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=2)

In [16]:
X_train.sample(5)

Age     Fare
16    2.0  29.1250
582  54.0  26.0000
98   34.0  23.0000
694  60.0  26.5500
704  26.0   7.8542

In [18]:
si = SimpleImputer()
X_train_trf = si.fit_transform(X_train)
X_test_trf = si.transform(X_test)

In [22]:
X_train_trf

array([[ 40.        ,  27.7208    ],
       [  4.        ,  16.7       ],
       [ 47.        ,   9.        ],
       ...,
       [ 71.        ,  49.5042    ],
       [ 29.78590426, 221.7792    ],
       [ 29.78590426,  25.925     ]])

In [24]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()

clf.fit(X_train_trf, y_train)
y_prd = clf.predict(X_test_trf)
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_prd))

0.6145251396648045


In [30]:
Mi = MissingIndicator()

In [32]:
Mi.fit(X_train)

MissingIndicator()

In [34]:
Mi.features_

array([0], dtype=int64)

In [36]:
X_train_missing = Mi.transform(X_train)

In [38]:
X_train_missing

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [

In [40]:
X_test_missing = Mi.transform(X_test)

In [42]:
X_train['Age_NA'] = X_train_missing

In [48]:
X_test['Age_NA'] = X_test_missing

In [44]:
X_train

Age      Fare  Age_NA
30   40.0   27.7208   False
10    4.0   16.7000   False
873  47.0    9.0000   False
182   9.0   31.3875   False
876  20.0    9.8458   False
..    ...       ...     ...
534  30.0    8.6625   False
584   NaN    8.7125    True
493  71.0   49.5042   False
527   NaN  221.7792    True
168   NaN   25.9250    True

[712 rows x 3 columns]

In [50]:
si = SimpleImputer()

X_train_trf2 = si.fit_transform(X_train)
X_test_trf2 = si.transform(X_test)

In [52]:
clf = LogisticRegression()
clf.fit(X_train_trf2, y_train)
y_prd2 = clf.predict(X_test_trf2)

accuracy_score(y_test, y_prd2)

0.6312849162011173