In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
df = pd.read_csv('/kaggle/input/heart-disease-cleveland-uci/heart_cleveland_upload.csv')

FileNotFoundError: [Errno 2] No such file or directory: '/kaggle/input/heart-disease-cleveland-uci/heart_cleveland_upload.csv'

In [ ]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   69    1   0       160   234    1        2      131      0      0.1      1   
1   69    0   0       140   239    0        0      151      0      1.8      0   
2   66    0   0       150   226    0        0      114      0      2.6      2   
3   65    1   0       138   282    1        2      174      0      1.4      1   
4   64    1   0       110   211    0        2      144      1      1.8      1   

   ca  thal  condition  
0   1     0          0  
1   2     0          0  
2   0     0          0  
3   1     0          1  
4   0     0          0

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns = 'condition'), df['condition'], test_size = 0.2, random_state=42)

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [ ]:

clf1 = LogisticRegression()
clf2 = DecisionTreeClassifier()

In [ ]:

clf1.fit(X_train, y_train)
clf2.fit(X_train, y_train)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


DecisionTreeClassifier()

In [ ]:

y_pred1 = clf1.predict(X_test)
y_pred2 = clf2.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [ ]:
print('accuracy score LR::::::::', accuracy_score(y_test, y_pred1))
print('accuracy score DT::::::::', accuracy_score(y_test, y_pred2))

accuracy score LR:::::::: 0.7333333333333333
accuracy score DT:::::::: 0.7166666666666667


In [ ]:
confusion_matrix(y_test, y_pred1)

array([[23,  9],
       [ 7, 21]])

In [ ]:
print("Logistic Regression Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,2)))


Logistic Regression Confusion Matrix



0   1
0  23   9
1   7  21

In [ ]:
print("Decision Regressison Cofusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test, y_pred2), columns=list(range(0,2)))

Decision Regressison Cofusion Matrix



0   1
0  22  10
1   7  21

In [ ]:

result = pd.DataFrame()
result['Actual Label'] = y_test
result['Logistic Regression Prediction'] = y_pred1
result['Decision Tree Prediction'] = y_pred2



In [ ]:
result.sample(10)

Actual Label  Logistic Regression Prediction  Decision Tree Prediction
116             0                               0                         0
6               0                               0                         0
275             0                               1                         0
167             1                               1                         1
237             1                               1                         1
17              0                               1                         0
285             0                               0                         0
45              1                               1                         1
84              0                               0                         0
42              0                               0                         1

In [ ]:
from sklearn.metrics import precision_score, recall_score, f1_score

In [ ]:

print("For Logistic regression Model")
print("-"*50)
cdf = pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,2)))
print(cdf)
print("-"*50)
print("Precision - ",precision_score(y_test,y_pred1))
print("Recall - ",recall_score(y_test,y_pred1))
print("F1 score - ",f1_score(y_test,y_pred1))


For Logistic regression Model
--------------------------------------------------
    0   1
0  23   9
1   7  21
--------------------------------------------------
Precision -  0.7
Recall -  0.75
F1 score -  0.7241379310344827


In [ ]:

print("For DT Model")
print("-"*50)
cdf = pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,2)))
print(cdf)
print("-"*50)
print("Precision - ",precision_score(y_test,y_pred2))
print("Recall - ",recall_score(y_test,y_pred2))
print("F1 score - ",f1_score(y_test,y_pred2))


For DT Model
--------------------------------------------------
    0   1
0  22  10
1   7  21
--------------------------------------------------
Precision -  0.6774193548387096
Recall -  0.75
F1 score -  0.7118644067796611


In [ ]:
precision_score(y_test, y_pred1, average=None)

array([0.76666667, 0.7       ])

In [ ]:
precision_score(y_test, y_pred2, average=None)

array([0.75862069, 0.67741935])

In [ ]:
recall_score(y_test, y_pred2, average=None)

array([0.6875, 0.75  ])